// Part of PMData: https://pmdata.machinezoo.com
@NoTests
@NoDocs
@DraftApi
@ApiIssue("Integrate with hookless once hookless gets persistent dependency versions. Reactively block by default. Non-blocking code on UI level.")
@ApiIssue("Actual synchronous blocking outside reactive context and during nested cache access.")
@ApiIssue("Support read-only mode.")
@CodeIssue("Tolerate multiple processes accessing the same files.")
@CodeIssue("Use common ForkJoinPool. Easy to parallelize, even recursively. Submitter thread limits submissions to number of CPUs, so retains control over priorities.")
@ApiIssue("No exclusive computations. Everything is parallelized.")
@ApiIssue("Support nice level. Otherwise prioritize most recent refresh request.")
@CodeIssue("Limit number of refresh requests generated by single UI element to number of processors. Do this separately for each nice level.")
package com.machinezoo.pmdata.caching;

import com.machinezoo.stagean.*;
